#cloud-config
runcmd:
  - echo 'Defaults:centos !requiretty' >> /etc/sudoers.d/888-vagrant-cloud-init-requiretty
  - 'yum install -y epel-release'
  - 'yum update -y'
  - 'yum install -y python-pip docker'
  - 'pip install awscli'
  - echo "Setting up AWS" 
  - 'mkdir /root/.aws'
  - echo '[default]' > /root/.aws/credentials
  - echo 'aws_secret_access_key = todo: Fill_IN_AWS_SEC_KEY' >> /root/.aws/credentials
  - echo 'aws_access_key_id = todo: Fill_IN_AWS_ACCESS_KEY' >> /root/.aws/credentials
  - 'service docker start'
  - 'systemctl enable docker'
  - 'touch /tmp/cloud-init-complete'
